{{- $values := .Values }}
{{- range $name, $certificate := .Values.certificates }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: {{ $certificate.name }}
   namespace: {{ $.Values.namespace }}
spec:
   secretName: {{ $certificate.name }}
   commonName: {{ $certificate.fqdn }}
   dnsNames:
   - {{ $certificate.fqdn }}
   issuerRef:
      name: {{ $.Values.issuer }}
      kind: ClusterIssuer

{{- end }}

