apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-secrets-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

