apiVersion: v1
kind: Secret
metadata:
  name: cert-sa-readonly-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: readonly-secrets-sa
type: kubernetes.io/service-account-token

